### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.xbill.DNS.Lookup

### ISSUE THREAD

**Issue by zzx769394358** [dnsjava/dnsjava#239] opened 2021-12-03 08:04 UTC
java.lang.NoClassDefFoundError: Could not initialize class org.xbill.DNS.Lookup

dnsjava version:  3.0.2
code:
         InetSocketAddress inetSocketAddress = new InetSocketAddress("127.0.0.1",53);
        Resolver resolver = new SimpleResolver(inetSocketAddress);
        Lookup lookup;
        try {
            lookup = new Lookup(host, Type.SRV);         // NoClassDefFoundError
        } catch (TextParseException e) {
            e.printStackTrace();
            throw new IllegalStateException("dns srv fail, host: " + host);
        }
        lookup.setResolver(resolver);
        Record[] records = lookup.run();

----------------------------------------------------------------------------------------------------------------------------
but sometimes the error  is :
java.lang.ClassNotFoundException: com.sun.jna.Memory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_281]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_281]
	at org.xbill.DNS.config.WindowsResolverConfigProvider$InnerWindowsResolverConfigProvider.initialize(WindowsResolverConfigProvider.java:53) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.config.WindowsResolverConfigProvider.initialize(WindowsResolverConfigProvider.java:108) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.ResolverConfig.<init>(ResolverConfig.java:84) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.ResolverConfig.refresh(ResolverConfig.java:74) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.ResolverConfig.<clinit>(ResolverConfig.java:59) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.ExtendedResolver.<init>(ExtendedResolver.java:146) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.Lookup.refreshDefault(Lookup.java:81) ~[dnsjava-3.0.2.jar:na]
	at org.xbill.DNS.Lookup.<clinit>(Lookup.java:88) ~[dnsjava-3.0.2.jar:na]

**Comment by ibauersachs** [comment] 2021-12-05 16:04
Duplicate of #112

Please use the newest version of dnsjava, currently v3.4.3.

**Closed by ibauersachs** 2021-12-05 16:04 UTC
