### ISSUE TITLE
dnsjava fails with client cookie

### ISSUE THREAD

**Issue by soufianbenafia** [dnsjava/dnsjava#236] opened 2021-11-22 17:08 UTC
Hello guys,

when making a request to the dns server with a client cookie following exception occurs. The Message class in dnsjava cannot handle a bytebuffer that includes client cookies.

`Message request = new Message(receiveBuffer.array());
`
```
Exception in thread "main" org.xbill.DNS.WireParseException: end of input
	at org.xbill.DNS.DNSInput.require(DNSInput.java:54)
	at org.xbill.DNS.DNSInput.readU16(DNSInput.java:154)
	at org.xbill.DNS.EDNSOption.fromWire(EDNSOption.java:165)
	at org.xbill.DNS.OPTRecord.rrFromWire(OPTRecord.java:84)
	at org.xbill.DNS.Record.newRecord(Record.java:82)
	at org.xbill.DNS.Record.fromWire(Record.java:191)
	at org.xbill.DNS.Message.<init>(Message.java:111)
	at org.xbill.DNS.Message.<init>(Message.java:143)
```

Request was made by following dig command:
`dig +qr  +edns +cookie @ip_adress -p Port_number domain`

**Comment by ibauersachs** [comment] 2021-11-22 17:31
This is probably the same as #224 / #225.

**Comment by soufianbenafia** [comment] 2021-11-23 14:42
is there any workaround for it ?

**Comment by ibauersachs** [comment] 2021-11-23 15:17
v3.4.1 was not affected. You might be able to downgrade if you're not affected by the bugs that were fixed in v3.4.2.

**Comment by ibauersachs** [comment] 2021-12-05 16:02
I've released v3.4.3 which includes a fix for the issues mentioned. I'm closing this assuming it was a duplicate. Let me know if there's still an issue in 3.4.3.

**Comment by soufianbenafia** [comment] 2021-12-07 12:47
Exception is still appearing

```
Exception in thread "main" org.xbill.DNS.WireParseException: end of input
        at org.xbill.DNS.DNSInput.require(DNSInput.java:54)
        at org.xbill.DNS.DNSInput.readU16(DNSInput.java:154)
        at org.xbill.DNS.Record.fromWire(Record.java:180)
        at org.xbill.DNS.Message.<init>(Message.java:111)
        at org.xbill.DNS.Message.<init>(Message.java:143)
        at DNS_Server.main(DNS_Server.java:61)
```

**Comment by ibauersachs** [comment] 2021-12-26 11:37
I can't reproduce this with neither v3.4.2 nor v3.4.3. I assume your server got an incomplete query, just like in #240. Here's a quick example that works just fine. If you still encounter issues please attach sample code to reproduce it.

```java
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import java.io.IOException;
import org.xbill.DNS.Message;
import org.xbill.DNS.Section;

public class Test2 {
  public static void main(String[] args) {
    Vertx v = Vertx.vertx();
    v.createDatagramSocket()
        .listen(1053, "0.0.0.0")
        .onSuccess(
            s ->
                s.handler(
                    h -> {
                      try {
                        Message in = new Message(h.data().getBytes());
                        System.out.println(in);
                        Message out = new Message(in.getHeader().getID());
                        out.addRecord(in.getQuestion(), Section.QUESTION);
                        s.send(
                            Buffer.buffer(out.toWire()),
                            h.sender().port(),
                            h.sender().hostAddress());
                      } catch (IOException e) {
                        e.printStackTrace();
                      }
                    }));
  }
}
```

```
$> dig +qr +edns +cookie @192.168.10.96 -p 1053

; <<>> DiG 9.16.1-Ubuntu <<>> +qr +edns +cookie @192.168.10.96 -p 1053
; (1 server found)
;; global options: +cmd
;; Sending:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42960
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a6f0d03fee9a0eec
;; QUESTION SECTION:
;.                              IN      NS

;; QUERY SIZE: 40

;; Warning: query response not set
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42960
;; flags:; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;.                              IN      NS

;; Query time: 90 msec
;; SERVER: 192.168.10.96#1053(192.168.10.96)
;; WHEN: Sun Dec 26 12:26:48 CET 2021
;; MSG SIZE  rcvd: 17
```

**Closed by ibauersachs** 2021-12-26 11:37 UTC
