### ISSUE TITLE
Possible bug in Cache.addMessage

### ISSUE THREAD

**Issue by jschewebbn** [dnsjava/dnsjava#151] opened 2021-01-20 23:11 UTC
If the message given to `Cache.addMessage` has 4 answers like this:

```
appP3N1.TLD.	1	IN	CNAME	appP3N1.S.TLD.
appP3N1.S.TLD.	1	IN	CNAME	appP3N1.Q.TLD.
appP3N1.Q.TLD.	1	IN	CNAME	Qserver02_c0.TLD.
Qserver02_c0.TLD.	86400	IN	A	10.0.4.12
```

I would expect that the returned `SetResponse` should have the type `SetResponse.SUCCESSFUL`. However due to the response being created inside the if branch for CNAME record, the returned value has the type `SetResponse.CNAME`.
This causes `Lookup.processResponse` to follow the CNAME records through the cache rather than just returning the value immediately.

I believe that the `response` object needs to be created from the last answer rather than the first answer.

**Comment by ibauersachs** [comment] 2021-01-21 07:56
I assume your query was for `appP3N1.TLD.`. I need to investigate this a bit better, but I think the current behavior is correct because the TTLs of the CNAMEs need to be honored.

**Comment by jschewebbn** [comment] 2021-01-21 13:36
Yes, the query was for `appP3N1.TLD.` I'm not sure what you mean about the TTLs of the CNAMEs being honored. If the client did a query for `appP3N1.TLD.` and got back the response here, where does the TTL come into play? I understand the TTL applies to how long the cache can hang onto the various pieces of this response, but that's already handled by putting the answers into the cache.

**Comment by ibauersachs** [comment] 2021-01-21 15:49
Maybe I misunderstood you. Do you refer to the first query for `appP3N1.TLD.` that is misbehaving? I was thinking about the second lookup attempt when the cache is already populated.

**Comment by jschewebbn** [comment] 2021-01-21 16:01
I'm referring to the initial query. As it stands right now, the query to the server is done, `processResponse` is returning a `SetResponse` with the type set to `CNAME` rather than `SUCCESSFUL`. This causes an unneeded search through the cache and the execution of the `follow` method.

**Comment by nresare** [comment] 2021-02-02 15:48
I believe that it works as intended. 

When querying a remote server, a single answer gets sent back containing several records, but the cache is normalised such that each record is stored individually and looked up individually. Multiple cache lookups to resolve a record with a chain of CNAME indirections is normal and should be very fast.

**Comment by jschewebbn** [comment] 2021-02-02 15:52
2 reasons to not do this:
1. it's even faster to not do the cache looukp at all
2. this avoids problems with large CNAME chains that a server chooses to follow for you

**Comment by nresare** [comment] 2021-02-02 18:44
While a lookup for a name that traverses a chain of CNAME lookups might make a handful of roundtrips to the cache, it would require a significant redesign of the structure of the Cache implementation to store the whole CNAME chain keyed by the lookup (currently it only stores RRset or negative cache values). Such an implementation would need to deal with different records having different TTL values (It is quite common for DNS based geo location setups to have some CNAMEs have short TTLs and others have long ones). All of this, to what end? A million cache lookups on my laptop here takes ~200ms.

**Comment by jschewebbn** [comment] 2021-02-02 18:47
I wasn't thinking the cache lookup would need to be changed. Just return the value from the method directly. I agree it's not worth rewriting the cache system for such a thing.

**Comment by ibauersachs** [comment] 2021-02-02 22:10
Return which response directly? The `Message` coming in from the resolver is not the same as what is returned from the cache. I had a look at the stuff yesterday and it's too convoluted to change for, as Noa correctly states, nothing. The long CNAME chains you're referring to are an anomaly, and nobdy in their right mind would create a longer than 5-6 CNAMEs. Given BINDs popularity, I don't think you'd get many responses that even go beyond the hard limit of 16.

I'm going to close this issue. If you're up for a pull request though, I'll certainly have a look.

**Closed by ibauersachs** 2021-02-02 22:10 UTC
