### ISSUE TITLE
Calling a lot of lookups in parallel makes all of them timeout

### ISSUE THREAD

**Issue by klaraward** [dnsjava/dnsjava#211] opened 2021-08-20 14:01 UTC
One of our use cases make a lot (~30) lookups in parallel, and it seems that they either all succeed or all timeout depending on how we tweek the timeout for the ExtendedResolver.  We use a 5 second timeout as the default, but can make the lookups succeed if we raise it a bit. 

Our theory is that the lookups are resolved in the ForkJoin common pool, which is also busy with other work so all lookups will take a bit longer to complete, making them all fall outside the timeout limit.

Should we just raise the timeout, or could the behavior of dnsjava be improved?

We read #206 but were not sure if that would affect the behavior of multiple unrelated lookups or not.

We have a reproducer just using dnsjava which I will include.

**Comment by klaraward** [comment] 2021-08-20 14:04
Reproducer which will timeout all lookups, can be tweaked with a higher ExtendedResolver timeout to pass

```
import java.time.Duration;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import org.xbill.DNS.DClass;
import org.xbill.DNS.ExtendedResolver;
import org.xbill.DNS.Lookup;
import org.xbill.DNS.TextParseException;
import org.xbill.DNS.Type;

public class Application {
  private static AtomicInteger failureCount = new AtomicInteger(0);

  public static void main(String[] args) throws InterruptedException {
    int numThreads = 50;
    final var smallExecutorService = Executors.newFixedThreadPool(5);
    final var executorService = Executors.newFixedThreadPool(numThreads);
    var records = List.of("one.one.one.one.",
                                "dns.quad9.net.",
                                "dns11.quad9.net.",
                                "lookup1.resolver.lax-noc.com.",
                                "b.resolvers.Level3.net.",
                                "dns1.nextdns.io.",
                                "dns2.nextdns.io.",
                                "resolver.qwest.net.",
                                "dns1.ncol.net.",
                                "ny.ahadns.net.",
                                "dns1.puregig.net.",
                                "primary.dns.bright.net.",
                                "edelta2.DADNS.america.net.",
                                "ns2.frii.com.",
                                "dns3.dejazzd.com.",
                                "ns7.dns.tds.net.",
                                "ns1.ceinetworks.com.",
                                "nsorl.fdn.com.",
                                "dns2.norlight.net.",
                                "safeservedns.com.",
                                "unkname.unk.edu.",
                                "redirect.centurytel.net.",
                                "dns2.nextdns.io.",
                                "Edelta.DADNS.america.net.",
                                "gatekeeper.poly.edu.",
                                "ns1.wavecable.com.",
                                "ns2.wavecable.com.",
                                "nrcns.s3woodstock.ga.atlanta.comcast.net.",
                                "resolver1.opendns.com.",
                                "cns1.Atlanta2.Level3.net.",
                                "redirect.centurytel.net.",
                                "x.ns.gin.ntt.net.",
                                "rec1pubns2.ultradns.net.",
                                "dns2.dejazzd.com.",
                                "c.resolvers.level3.net.",
                                "dnscache2.izoom.net.",
                                "ns2.nyc.pnap.net.",
                                "yardbird.cns.vt.edu.",
                                "cns4.Atlanta2.Level3.net.",
                                "nscache.prserv.net.",
                                "nscache07.us.prserv.net.",
                                "hvdns1.centurylink.net.",
                                "a.resolvers.level3.net.",
                                "ns2.socket.net.",
                                "res1.dns.cogentco.com.",
                                "rdns.dynect.net.");

    CountDownLatch done = new CountDownLatch(records.size() * 2);
    records.stream()
        .forEach(
            fqdn -> {
              executorService.submit(() -> resolve(fqdn, done));
              CompletableFuture.runAsync(Application::blockCommonPool)
                  .whenComplete((v, ex) -> done.countDown());
            });
    done.await(1, TimeUnit.MINUTES);
    executorService.shutdown();

    System.out.println("Number of threads: " + numThreads);
    System.out.println("Number of records: " + records.size());
    System.out.println("Failed lookups: " + failureCount);
  }

  private static void blockCommonPool() {
    try {
      Thread.sleep(1_000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }

  private static void resolve(String fqdn, CountDownLatch done) {
    try {
      System.out.println("Resolving: " + fqdn);
      Lookup lookup = forName(fqdn);
      lookup.run();

      switch (lookup.getResult()) {
        case Lookup.SUCCESSFUL:
          System.out.println(fqdn + "...ok!");
          break;
        case Lookup.HOST_NOT_FOUND:
        case Lookup.TYPE_NOT_FOUND:
          System.out.format("No results returned for query '%s'; result from XBill: %s - %s",
                            fqdn, lookup.getResult(), lookup.getErrorString());
          break;
        default:
          failureCount.incrementAndGet();
          throw new RuntimeException(
              String.format("Lookup of '%s' failed with code: %d - %s ",
                  fqdn, lookup.getResult(), lookup.getErrorString()));
      }
    } catch (Exception e) {
      System.err.format("%s ... failed!\n", fqdn);
      e.printStackTrace(System.err);
    } finally {
      done.countDown();
    }
  }

  public static Lookup forName(String fqdn) {
    try {
      final Lookup lookup = new Lookup(fqdn, Type.A, DClass.IN);
      final var resolver = new ExtendedResolver();
      resolver.setTimeout(Duration.ofMillis(5_000)); // Passes if raised a bit
      lookup.setResolver(resolver);
      return lookup;
    } catch (TextParseException e) {
      throw new RuntimeException("unable to create lookup for name: " + fqdn, e);
    }
  }
}
```

**Comment by ibauersachs** [comment] 2021-08-20 14:53
Thanks for the detailed report. I'll need some time to look at this, but in the meantime please try the following modifications. It might still fail though.

- The resolvers are meant to be kept around for multiple lookup and are thread safe. So, create one `ExtendedResolver`, and reuse it for all `Lookup`s.
- You might want to try the new async [LookupSession](https://javadoc.io/static/dnsjava/dnsjava/3.4.1/index.html?org/xbill/DNS/lookup/LookupSession.html) instead of the older synchronous `Lookup`

**Comment by klaraward** [comment] 2021-08-23 07:54
Tried reusing the ExtendedResolver but problem persists.

Using the LookupSession might be worth a try for us, but would be nice to know if there was also a quick fix that would be able the to bridge this problem for a bit.

For the record, in our real use case, we use `dnsjava` from our own wrapper library https://github.com/spotify/dns-java, and the using code calls
```
            DnsSrvResolvers.newBuilder()
                           .retainingDataOnFailures(false)
                           .cachingLookups(false)
                           .build());
```

And then `dnsSrvResolve.resolve()`

We believe that the stripped down repro is pretty close to mimicking the behavior we get when many records are being resolved in parallel.

**Comment by ibauersachs** [comment] 2021-08-23 08:48
I was able to reproduce it with your example (using a lower timeout). The problem with `Lookup` is that it runs synchronously and this implicitly uses `CompletableFuture.get()`. While fixing/investigating I concentrated on the usage with `LookupSession`, but unfortunately found a severe bug in there as well (CNAMEs are not properly handled). 
I'm not sure yet why all lookups fail when the threadpool is busy, but I would certainly expect some of them to timeout. But it might be worth another discussion on how timeouts are expected to be handled, see e.g. the explanation in #206.

**Comment by klaraward** [comment] 2021-08-23 15:03
Would letting Lookup/Resolver (especially the handleAsync call in Resolver) run in a custom provided executor make any sense?

We tried to make that change ourselves, currently experiencing some weird behavior which seems to fix things just by calling ForkJoinPool.commonPool() without actually using it. Investigating further.

**Comment by ibauersachs** [comment] 2021-08-23 15:12
Possibly, do you mean adding a method in `Resolver` like `CompletionStage<Message> sendAsync(Message query, ExecutorService executor)`?

I noted that your linked project is/was still on an old version of dnsjava. I assume whatever you're testing with locally uses the current 3.4.1?

**Comment by klaraward** [comment] 2021-08-23 15:16
Exactly that method yes.

We are using 3.4.1 for local repros yes, even tried out the latest in master of this repo.

**Comment by klaraward** [comment] 2021-08-24 13:38
The weird behavior I mentioned when trying to add the executor was my bad, it just created a StackOverflowError where the sendAsync methods in the Resolver interface kept calling eachother but never called the sendAsync method in the implementing classes :)

For now we have gone for exposing setting the timeout in the application framework layers we have on top of dnsjava, so that services that need that can raise the timeout.

**Comment by ibauersachs** [comment] 2021-08-24 15:35
Well, the default implementations are a bit weird, but it was the only way to keep backwards compatibility. Did the solution with a different ExecutorService work when you correctly implemented the change?

Customizing the timeout is surely a good idea, but I would assume it won't be a reliable solution. I'll see what I can do about `Lookup`, but my efforts will first go into fixing `LookupSession`.

**Comment by ibauersachs** [comment] 2021-08-29 17:54
I'm working on implementing overloads to pass a custom `Executor` in the `Resolver`s. I won't be adding any support for this in `Lookup` however, but I sent you a pull request (spotify/dns-java#46) that demonstrates the use of `LookupSession`. I think it would be well worth it to follow up on this and get rid of the old, synchronous Lookup, especially since you're already running mostly async code. You can also work with dnsjava 3.4.1 instead of the current SNAPSHOT until 3.4.2 is finished, the CNAME bug as mentioned in #212 shouldn't affect you as you're only querying for SRV.

It's also worth mentioning that the deadlock-like behavior only occurs on Java 11. Java 8 works more or less as expected: some queries succeed, some fail.

**Closed** 2021-09-19 16:31 UTC
Labels: bug
