### ISSUE TITLE
Getting No Records Found

### ISSUE THREAD

**Issue by zentech** [dnsjava/dnsjava#61] opened 2019-06-16 21:48 UTC
I'm using the library on android and I keep getting "no records found" when searching for records on domain like google.com and yahoo.com

**Comment by kingle** [comment] 2019-06-19 06:24
See issue #6 
Starting with Android O, the old mechanism used to discover DNS servers from the device was removed.  As a workaround, you could set the `dns.server` system property and give it a comma delimited list of DNS servers.  For example, you might consider supplying the Google Public DNS servers:
`dns.server=8.8.8.8,8.8.4.4`

**Comment by ibauersachs** [comment] 2019-09-02 22:57
Duplicate of #6

**Closed by ibauersachs** 2019-09-02 22:57 UTC
